In [2]:
!pip install tensorflow

     |████████████████████████████████| 454.4 MB 56 kB/s  eta 0:00:015   |██▍                             | 33.9 MB 4.2 MB/s eta 0:01:41     |██▋                             | 37.5 MB 4.2 MB/s eta 0:01:40     |███▋                            | 52.0 MB 4.7 MB/s eta 0:01:26     |████▍                           | 61.8 MB 7.5 MB/s eta 0:00:53     |█████▎                          | 74.6 MB 7.3 MB/s eta 0:00:52     |████████                        | 112.4 MB 4.0 MB/s eta 0:01:25     |█████████▉                      | 138.9 MB 3.5 MB/s eta 0:01:30     |███████████▍                    | 161.1 MB 919 kB/s eta 0:05:20     |███████████████▉                | 225.5 MB 4.2 MB/s eta 0:00:55     |████████████████▋               | 235.2 MB 4.8 MB/s eta 0:00:46     |█████████████████               | 241.5 MB 3.6 MB/s eta 0:01:00     |███████████████████             | 271.2 MB 6.4 MB/s eta 0:00:29     |███████████████████▎            | 273.1 MB 6.4 MB/s eta 0:00:29     |████████████████████████▎       | 

      Successfully uninstalled numpy-1.20.3
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.2.1
    Uninstalling h5py-3.2.1:
      Successfully uninstalled h5py-3.2.1


In [170]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
np.random.seed(777)

In [171]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [172]:
train_no_predict = train_df.drop(['id', 'target'], 1)
train_predict = train_df['target']

train_percent = 0.80

X_train, X_test, y_train, y_test = train_test_split(train_no_predict, train_predict, stratify=train_predict, train_size=train_percent)
print('train count: ', len(y_train))
print('test count: ', len(y_test))

train count:  160000
test count:  40000


In [173]:
encoder = LabelEncoder()
encoder.fit(y_train)
encoded_Y = encoder.transform(y_train)
dummy_y = np_utils.to_categorical(encoded_Y)

dummy_y = dummy_y.astype(int)
y_dim = np.shape(dummy_y)[1]
print(dummy_y)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [174]:
X_train = X_train.values.astype(int)
X_dim = np.shape(X_train)[1]
print(X_train)

[[ 0  0  0 ...  1  0  0]
 [ 1  0  1 ...  0  1  0]
 [ 3  0  0 ...  1  0  0]
 ...
 [ 1  0 13 ...  0  2  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  1 ...  1  0  0]]


In [175]:
hidden_nodes = 10

def baseline_model():
    model = Sequential()
    model.add(Dense(hidden_nodes, input_dim=X_dim, activation='relu'))
    model.add(Dense(y_dim, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [176]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=60, batch_size=256, verbose=2)

In [177]:
kfold = KFold(n_splits=25, shuffle=True, random_state=777)
#skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=777)

In [ ]:
import datetime;
print(datetime.datetime.now())

grid_search = GridSearchCV(estimator = estimator, cv = kfold, param_grid = {})
grid_search = grid_search.fit(X_train, dummy_y)

print(datetime.datetime.now())

2021-06-21 01:34:50.423832
Epoch 1/60
600/600 - 1s - loss: 2.4171 - accuracy: 0.2338
Epoch 2/60
600/600 - 1s - loss: 1.9435 - accuracy: 0.2808
Epoch 3/60
600/600 - 1s - loss: 1.8816 - accuracy: 0.3123
Epoch 4/60
600/600 - 1s - loss: 1.8411 - accuracy: 0.3329
Epoch 5/60
600/600 - 1s - loss: 1.8199 - accuracy: 0.3400
Epoch 6/60
600/600 - 1s - loss: 1.8068 - accuracy: 0.3425
Epoch 7/60
600/600 - 1s - loss: 1.7998 - accuracy: 0.3425
Epoch 8/60
600/600 - 1s - loss: 1.7966 - accuracy: 0.3434
Epoch 9/60
600/600 - 1s - loss: 1.7951 - accuracy: 0.3432
Epoch 10/60
600/600 - 1s - loss: 1.7938 - accuracy: 0.3446
Epoch 11/60
600/600 - 1s - loss: 1.7926 - accuracy: 0.3458
Epoch 12/60
600/600 - 1s - loss: 1.7911 - accuracy: 0.3468
Epoch 13/60
600/600 - 1s - loss: 1.7901 - accuracy: 0.3472
Epoch 14/60
600/600 - 1s - loss: 1.7891 - accuracy: 0.3482
Epoch 15/60
600/600 - 1s - loss: 1.7883 - accuracy: 0.3474
Epoch 16/60
600/600 - 1s - loss: 1.7875 - accuracy: 0.3488
Epoch 17/60
600/600 - 1s - loss: 1.787

Epoch 19/60
600/600 - 1s - loss: 1.7902 - accuracy: 0.3486
Epoch 20/60
600/600 - 1s - loss: 1.7898 - accuracy: 0.3483
Epoch 21/60
600/600 - 1s - loss: 1.7893 - accuracy: 0.3486
Epoch 22/60
600/600 - 1s - loss: 1.7886 - accuracy: 0.3487
Epoch 23/60
600/600 - 1s - loss: 1.7880 - accuracy: 0.3491
Epoch 24/60
600/600 - 1s - loss: 1.7876 - accuracy: 0.3488
Epoch 25/60
600/600 - 1s - loss: 1.7871 - accuracy: 0.3490
Epoch 26/60
600/600 - 1s - loss: 1.7866 - accuracy: 0.3494
Epoch 27/60
600/600 - 1s - loss: 1.7861 - accuracy: 0.3492
Epoch 28/60
600/600 - 1s - loss: 1.7859 - accuracy: 0.3498
Epoch 29/60
600/600 - 1s - loss: 1.7857 - accuracy: 0.3494
Epoch 30/60
600/600 - 1s - loss: 1.7852 - accuracy: 0.3496
Epoch 31/60
600/600 - 1s - loss: 1.7849 - accuracy: 0.3498
Epoch 32/60
600/600 - 1s - loss: 1.7847 - accuracy: 0.3495
Epoch 33/60
600/600 - 1s - loss: 1.7846 - accuracy: 0.3497
Epoch 34/60
600/600 - 1s - loss: 1.7843 - accuracy: 0.3495
Epoch 35/60
600/600 - 1s - loss: 1.7842 - accuracy: 0.35

Epoch 37/60
600/600 - 1s - loss: 1.7782 - accuracy: 0.3512
Epoch 38/60
600/600 - 1s - loss: 1.7779 - accuracy: 0.3506
Epoch 39/60
600/600 - 1s - loss: 1.7777 - accuracy: 0.3518
Epoch 40/60
600/600 - 1s - loss: 1.7779 - accuracy: 0.3513
Epoch 41/60
600/600 - 1s - loss: 1.7776 - accuracy: 0.3506
Epoch 42/60
600/600 - 1s - loss: 1.7775 - accuracy: 0.3512
Epoch 43/60
600/600 - 1s - loss: 1.7773 - accuracy: 0.3512
Epoch 44/60
600/600 - 1s - loss: 1.7772 - accuracy: 0.3509
Epoch 45/60
600/600 - 1s - loss: 1.7773 - accuracy: 0.3510
Epoch 46/60
600/600 - 1s - loss: 1.7772 - accuracy: 0.3511
Epoch 47/60
600/600 - 1s - loss: 1.7769 - accuracy: 0.3502
Epoch 48/60
600/600 - 1s - loss: 1.7768 - accuracy: 0.3505
Epoch 49/60
600/600 - 1s - loss: 1.7764 - accuracy: 0.3512
Epoch 50/60
600/600 - 1s - loss: 1.7765 - accuracy: 0.3510
Epoch 51/60
600/600 - 1s - loss: 1.7762 - accuracy: 0.3512
Epoch 52/60
600/600 - 1s - loss: 1.7761 - accuracy: 0.3509
Epoch 53/60
600/600 - 1s - loss: 1.7760 - accuracy: 0.35

In [154]:
encoder = LabelEncoder()
encoder.fit(y_test)
encoded_Y = encoder.transform(y_test)
test_dummy_y = np_utils.to_categorical(encoded_Y)

test_dummy_y = test_dummy_y.astype(int)
test_y_dim = np.shape(test_dummy_y)[1]

X_test = X_test.values.astype(int)

test_probs = grid_search.predict_proba(X_test)
the_log_loss = abs(log_loss(test_dummy_y, test_probs))
print(the_log_loss)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
157/157 [==============================] - 0s 939us/step
1.8434893054716288
